import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  weight:["400","500","600","700"],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Foodiland",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
